logs = read.csv("logs.csv")
attach(logs)
png("stateplot.png", height=960)
par(mfrow=c(10,5))
par(mar=c(0,0,1,0))
plot(akrank,akpop, main="AK", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(alrank,alpop, main="AL", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(arrank,arpop, main="AR", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(azrank,azpop, main="AZ", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(carank,capop, main="CA", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(corank,copop, main="CO", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(ctrank,ctpop, main="CT", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(derank,depop, main="DE", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(flrank,flpop, main="FL", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(garank,gapop, main="GA", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(hirank,hipop, main="HI", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(iarank,iapop, main="IA", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(idrank,idpop, main="ID", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(ilrank,ilpop, main="IL", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(inrank,inpop, main="IN", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(ksrank,kspop, main="KS", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(kyrank,kypop, main="KY", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(larank,lapop, main="LA", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(marank,mapop, main="MA", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(mdrank,mdpop, main="MD", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(merank,mepop, main="MA", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(mirank,mipop, main="MI", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(mnrank,mnpop, main="MN", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(morank,mopop, main="MO", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(msrank,mspop, main="MS", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(mtrank,mtpop, main="MT", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(ncrank,ncpop, main="NC", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(ndrank,ndpop, main="ND", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(nerank,nepop, main="NE", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(nhrank,nhpop, main="NH", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(njrank,njpop, main="NJ", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(nmrank,nmpop, main="NM", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(nvrank,nvpop, main="NV", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(nyrank,nypop, main="NY", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(ohrank,ohpop, main="OH", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(okrank,okpop, main="OK", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(orrank,orpop, main="OR", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(parank,papop, main="PA", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(rirank,ripop, main="RI", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(scrank,scpop, main="SC", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(sdrank,sdpop, main="SD", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(tnrank,tnpop, main="TN", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(txrank,txpop, main="TX", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(utrank,utpop, main="UT", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(varank,vapop, main="VA", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(vtrank,vtpop, main="VT", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(warank,wapop, main="WA", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(wirank,wipop, main="WI", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(wvrank,wvpop, main="WV", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
plot(wyrank,wypop, main="WY", xlab="", ylab="", pch=16, xaxt="n", yaxt="n")
dev.off()